### ISSUE TITLE
How to build and use gml-copy-dlls/main.go applicaiton?

### ISSUE THREAD

**Issue by carlos22** [desertbit/gml#2]
I'm unable to build or use the gml-copy-dlls application. go get only provides the gml app and building fails due to the internal/utils usage.

Thanks for any help.

**Comment by r0l1** [comment]
Hi @carlos22 
Please try:

```
go get -u github.com/desertbit/gml/cmd/gml-copy-dlls
```

The binary will be installed into your go bin directory,

**Comment by carlos22** [comment]
This helps a lot. Thanks. Very cool tool btw. - works a lot better than the other scripts we used before.
